import type { Metadata } from "next";
import "./globals.scss";
import { Providers } from "./providers";
import HeaderWrapper from "./HeaderWrapper";

export const metadata: Metadata = {
  title: "Leave management system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <HeaderWrapper />
          {children}
        </Providers>
      </body>
    </html>
  );
}
